module FrontEnd.Prelude(findPrelude, defaultPrelude) where
import FrontEnd.Expr
import FrontEnd.Parse

findPrelude :: String -> Either String (String, Expr)
findPrelude pn =
  case lookup pn preludes of
    Nothing -> Left $ "prelude " ++ pn ++ " not found"
    Just file ->
      case parseTry pFile pn file of
        Left msg -> Left $ "bad prelude " ++ msg
        Right e  -> Right (pn, e)

defaultPrelude :: String
defaultPrelude = "miniprelude"

preludes :: [(String, String)]
preludes = [noprelude, miniprelude, verifyprelude, verifyabsprelude, mediumprelude]

-- Do not edit anything below.
-- It's generated by the Makefile
-- snip -- snip --

noprelude :: (String, String)
noprelude = ("noprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Empty prelude\n\
\array{}\n\
\")

miniprelude :: (String, String)
miniprelude = ("miniprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Small prelude with no checking of arithmetic.\n\
\array{\n\
\operator'+'      := intAdd$;\n\
\operator'-'      := intSub$;\n\
\operator'*'      := intMul$;\n\
\operator'/'      := intDiv$;\n\
\prefix'-'        := intNeg$;\n\
\prefix'+'        := intPlus$;\n\
\operator'<'      := intLT$;\n\
\operator'<='     := intLE$;\n\
\operator'>'      := intGT$;\n\
\operator'>='     := intGE$;\n\
\operator'<>'     := intNE$;\n\
\any              := any$;\n\
\int(_x:any$)<decides>         := { isInt$[_x]; _x };\n\
\rational(_x:any$)<decides>    := { isRat$[_x]; _x };\n\
\string(_x:any$)<decides>      := { isStr$[_x]; _x };\n\
\char(_x:any$)<decides>        := { isChr$[_x]; _x };\n\
\nat(_x:any$)<decides>         := { isInt$[_x]; intGE$[_x,0]; _x };\n\
\operator'->'(_s:any$, _t:any$)(_g:any$)<decides> := function(_x:any$){isFcn$[_g]; _t[_g[_s[_x]]]};\n\
\false                       := array{};\n\
\postfix'^'(_p:any$)<reads><decides>  := read$[_p];\n\
\operator'.='(_p:any$,_x:any$)<writes><decides> := write$[_p, _x];\n\
\new := function(_t:any$)(_x:any$)<alloc><decides>{ alloc$[_t[_x]] };\n\
\}\n\
\\n\
\")

verifyprelude :: (String, String)
verifyprelude = ("verifyprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Small prelude for verification; arithmetic functions are concrete.\n\
\## The lowered{} macro stops insertion lowering from BigCore to Core,\n\
\## i.e., stop assume{} being inserted.\n\
\array{\n\
\false        := array{};\n\
\any          := lowered{ lambda(_x){                                                        assume { _x }}};\n\
\int          := lowered{ lambda(_x){                isInt$[_x];                             assume { _x }}};\n\
\char         := lowered{ lambda(_x){                isChr$[_x];                             assume { _x }}};\n\
\nat          := lowered{ lambda(_x){                isInt$[_x];             intGE$[_x,0];   assume { _x }}};\n\
\operator'+'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z := intAdd$[_x,_y]; isInt$[_z]; _z }}};\n\
\operator'-'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z := intSub$[_x,_y]; isInt$[_z]; _z }}};\n\
\operator'*'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z := intMul$[_x,_y]; isInt$[_z]; _z }}};\n\
\operator'/'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intNE$[_y, 0];  assume { _z := intDiv$[_x,_y]; isInt$[_z]; _z }}};\n\
\operator'<'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intLT$[_x, _y]; assume { isInt$[_x]; _x }}};\n\
\operator'<=' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intLE$[_x, _y]; assume { isInt$[_x]; _x }}};\n\
\operator'>'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intGT$[_x, _y]; assume { isInt$[_x]; _x }}};\n\
\operator'>=' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intGE$[_x, _y]; assume { isInt$[_x]; _x }}};\n\
\operator'<>' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intNE$[_x, _y]; assume { isInt$[_x]; _x }}};\n\
\}\n\
\")

verifyabsprelude :: (String, String)
verifyabsprelude = ("verifyabsprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Small prelude for verification; arithmetic functions are abstract.\n\
\## The lowered{} macro stops insertion lowering from BigCore to Core,\n\
\## i.e., stop assume{} being inserted.\n\
\array{\n\
\false                                  := array{};\n\
\any(_x:any$)<succeeds>                 := _x;\n\
\int(_x:any$)<decides>                  := { isInt$[_x]; _x };\n\
\char(_x:any$)<decides>                 := { isChr$[_x]; _x };\n\
\nat(_x:any$)<decides>                  := { isInt$[_x]; intGE$[_x,0]; _x };\n\
\operator'+'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'-'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'*'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y];                 assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'/'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intNE$[_y, 0];  assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'<'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intLT$[_x, _y]; assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'<=' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intLE$[_x, _y]; assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'>'  := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intGT$[_x, _y]; assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'>=' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intGE$[_x, _y]; assume { _z : any$; isInt$[_z]; _z } } };\n\
\operator'<>' := lowered{ lambda(_xy){ (_x,_y):=_xy; isInt$[_x]; isInt$[_y]; intNE$[_x, _y]; assume { _z : any$; isInt$[_z]; _z } } };\n\
\}\n\
\")

mediumprelude :: (String, String)
mediumprelude = ("mediumprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Medium prelude\n\
\array{\n\
\\n\
\operator'+' (_x:rational, _y:rational)<open><succeeds>  := { ratAdd$[_x, _y] };\n\
\operator'-' (_x:rational, _y:rational)<open><succeeds>  := { ratSub$[_x, _y] };\n\
\operator'*' (_x:rational, _y:rational)<open><succeeds>  := { ratMul$[_x, _y] };\n\
\operator'/' (_x:rational, _y:rational)<open><decides>   := { ratNE$[_y, 0]; ratDiv$[_x, _y] };\n\
\prefix'-'   (_x:rational)             <open><succeeds>  := { ratNeg$[_x] };\n\
\prefix'+'   (_x:rational)             <open><succeeds>  := { ratPlus$[_x] };\n\
\operator'<' (_x:rational, _y:rational)<open><decides>   := { ratLT$[_x,_y] };\n\
\operator'<='(_x:rational, _y:rational)<open><decides>   := { ratLE$[_x,_y] };\n\
\operator'>' (_x:rational, _y:rational)<open><decides>   := { ratGT$[_x,_y] };\n\
\operator'>='(_x:rational, _y:rational)<open><decides>   := { ratGE$[_x,_y] };\n\
\operator'<>'(_x:rational, _y:rational)<open><decides>   := { ratNE$[_x,_y] };\n\
\\n\
\false                                             := array{};\n\
\any                                               := any$;\n\
\int         (_x:any$)                 <decides>   := { isInt$[_x]; _x };\n\
\rational    (_x:any$)                 <decides>   := { isRat$[_x]; _x };\n\
\f32         (_x:any$)                 <decides>   := { isF32$[_x]; _x };\n\
\f64         (_x:any$)                 <decides>   := { isF64$[_x]; _x };\n\
\string      (_x:any$)                 <decides>   := { isStr$[_x]; _x };\n\
\char        (_x:any$)                 <decides>   := { isChr$[_x]; _x };\n\
\nat         (_x:any$)                 <decides>   := { isInt$[_x]; ratGE$[_x,0]; _x };\n\
\\n\
\#operator'->'(_s:any$, _t:any$)(_g:any$)<decides> := function(_x:any$){isFcn$[_g]; _t[_g[_s[_x]]]};\n\
\postfix'^'(_p:any$)<reads><decides>  := read$[_p];\n\
\operator'.='(_p:any$,_x:any$)<writes><decides> := write$[_p, _x];\n\
\new := function(_t:any$)(_x:any$)<alloc><decides>{ alloc$[_t[_x]] };\n\
\}\n\
\")
