#BEGIN_TEMPLATE_SECTION HEADER
# Copyright Epic Games, Inc. All Rights Reserved.
#END_TEMPLATE_SECTION HEADER

#BEGIN_TEMPLATE_SECTION INCLUDES
using { /Verse.org/Simulation/Tags }
#END_TEMPLATE_SECTION INCLUDES

#Note: class type must be kept as 'verse_tag_template'
#BEGIN_TEMPLATE_SECTION TAG_CLASS_TEMPLATE
verse_derived_tag_template := class<abstract>(tag){}
#END_TEMPLATE_SECTION TAG_CLASS_TEMPLATE