module FrontEnd.Prelude(
    PreludeName,
    findPrelude,
    defaultPrelude
  ) where

import FrontEnd.Expr
import FrontEnd.Parse

type PreludeName = String  -- We have a bunch of named preludes

findPrelude :: PreludeName
            -> Either
                  String               -- Error message if non-existent
                  (PreludeName, SrcExpr)
findPrelude pn =
  case lookup pn preludes of
    Nothing -> Left $ "prelude " ++ pn ++ " not found"
    Just file ->
      case parseTry pFile pn file of
        Left msg -> Left $ "bad prelude " ++ msg
        Right e  -> Right (pn, e)

defaultPrelude :: PreludeName
defaultPrelude = "miniprelude"

preludes :: [(PreludeName, String)]
preludes = [noprelude, miniEvalPrelude, miniVerifyPrelude]

-- Do not edit anything below.
-- It's generated by the Makefile
-- snip -- snip --

noprelude :: (PreludeName, String)
noprelude = ("noprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Empty prelude\n\
\array{}\n\
\")

miniEvalPrelude :: (PreludeName, String)
-- This "miniprelude" uses already-lowered lambdas, rather than Source Verse,
-- to reduce clutter
miniEvalPrelude = ("miniprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Small prelude with no checking of arithmetic.\n\
\array{\n\
\false    := array{};\n\
\any      := lam y {            y };\n\
\int      := lam y { isInt$[y]; y };\n\
\rational := lam y { isRat$[y]; y };\n\
\string   := lam y { isStr$[y]; y };\n\
\char     := lam y { isChar$[y]; y };\n\
\nat      := lam y { isChar$[y]; intGE$[y,0]; y };\n\
\operator'+'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intAdd$[x,y] }};\n\
\operator'-'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intSub$[x,y] }};\n\
\operator'*'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intMul$[x,y] }};\n\
\operator'/'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intDiv$[x,y] }};\n\
\operator'<'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intLT$[x,y] }};\n\
\operator'<='     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intLE$[x,y] }};\n\
\operator'>'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intGT$[x,y] }};\n\
\operator'>='     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intGE$[x,y] }};\n\
\operator'<>'     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intNE$[x,y] }};\n\
\Length(_x:any$):=arrLen$[_x];\n\
\}\n\
\")

miniVerifyPrelude :: (PreludeName, String)
-- This "miniprelude" uses already-lowered lambdas, rather than Source Verse,
-- to reduce clutter
miniVerifyPrelude = ("miniverifyprelude", "\
\## Use FrontEnd/Makefile to update compiled prelude.\n\
\## Small prelude with no checking of arithmetic.\n\
\array{\n\
\false    := array{};\n\
\any      := lambda y { y };\n\
\int      := lambda y { isInt$[y]; y };\n\
\rational := lam y { isRat$[y]; y };\n\
\string   := lam y { isStr$[y]; y };\n\
\char     := lam y { isChar$[y]; y };\n\
\nat      := lam y { isChar$[y]; intGE$[y,0]; y };\n\
\operator'+'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; (x,y) >> some{ lam z { z = intAdd$[x,y]; isInt$[z]; z } }}};\n\
\operator'-'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; (x,y) >> some{int} }};\n\
\operator'*'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; (x,y) >> some{int} }};\n\
\operator'/'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intNE$[y,0]; (x,y) >> some{int} }};\n\
\operator'<'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intLT$[x,y] }};\n\
\operator'<='     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intLE$[x,y] }};\n\
\operator'>'      := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intGT$[x,y] }};\n\
\operator'>='     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intGE$[x,y] }};\n\
\operator'<>'     := lam p { exi x y { (x,y) = p; isInt$[x]; isInt$[y]; intNE$[x,y] }};\n\
\Length(_x:any$):=arrLen$[_x];\n\
\}\n\
\")