site_name: Verse Language Documentation
site_url: https://augustss.github.io/verse-paper/
site_description: Comprehensive documentation for the Verse programming language
site_author: Jan Vitek

repo_name: augustss/verse-paper
repo_url: https://github.com/augustss/verse-paper
edit_uri: edit/main/Book/docs/

theme:
  name: material
  logo: images/verse.png
  palette:
    scheme: slate  # Dark theme
    primary: black
    accent: deep orange
  features:
#    - content.footnote.tooltips
#    - navigation.tabs
    - search.suggest

markdown_extensions:
 - admonition
 - pymdownx.details
 - footnotes
 - pymdownx.highlight:
      default_lang: verse
      linenums: false
      pygments_style: monokai
 - pymdownx.superfences

plugins:
  - search

extra_css:
  - extra.css

nav:
  - Home: index.md
  - Overview: 00_overview.md
  - Built-in Types: 01_builtins.md
  - Composite Types: 02_composites.md
  - Functions: 03_functions.md
  - Operators: 04_operators.md
  - Expressions: 05_expressions.md
  - Control Flow: 06_control.md
  - Modules and Paths: 07_modules.md
  - Failure: 08_failure.md
  - Effects: 09_effects.md
  - Concurrency: 10_concurrency.md
  - Mutability: 11_mutability.md
  - Type System: 12_types.md
  - Persistable Types: 13_persistable.md
  - Access Specifiers: 14_access.md
  - Code Evolution: 15_evolution.md
  - Grammar: 16_grammar.md
  - "📚 Concept Index": concept_index.md

