TestParsing("S00","<#>$\n $");

// Comments.
TestParsing("S00","");
TestParsing("S00"," ");
TestParsing("S00","\t");
TestParsing("S00","\n");
TestParsing("S00","<#abc#>");
TestParsing("S00","\n<#\n#>\n123");
TestParsing("S02","<#\xFF#>");
TestParsing("S32","\"X\xFFX\"");
TestParsing("S04","<#blah");
TestParsing("S04","<#blah<#blah#>");
TestParsing("S02","<#\b");
TestParsing("S00","<#blah<#blah#>#>");
TestParsing("S05","#>");
TestParsing("S05","##>");
TestParsing("S05","# #>");
TestParsing("S00","#abc");
TestParsing("S00","<#>");
TestParsing("S00","<#> $\n $\n $");
TestParsing("S05","<#>\n #>");
TestParsing("S04","<#>\n <#");
TestParsing("S04","# <#");
TestParsing("S00","# <# #> $");
TestParsing("S03","#\x03");
TestParsing("S06","<#>\x03");
TestParsing("S06","<#>\n 1\n 2\x03");
TestParsing("S02","<#\xFF");
TestParsing("S01","\xEF");
TestParsing("S00","");
TestParsing("S00"," ");
TestParsing("S00","#123\r\n #456 ");
TestParsing("S00"," <#abc<#def#>ghi#> ");
TestParsing("S00"," <#  a   \n    #>     ");
TestParsing("S00"," <#>%\n  %\n  %\n ");

// Constants.
TestParsing("S00","0");
TestParsing("S00","123178239817238123");
TestParsing("S00","0x123178239817238123");
TestParsing("S15","0x1AG");
TestParsing("S15","0x1A.5");
TestParsing("S77","0x1A$");
TestParsing("S77","0x1A\b");
TestParsing("S00","0x");
TestParsing("S00","0m");
TestParsing("S00","0kg");
TestParsing("S00","0uFFFFF");
TestParsing("S00","0u10FFFF");
TestParsing("S19","0u010FFFF");
TestParsing("S00","1e2h,1e2f,1e2d,1e2q");
TestParsing("S00","1e2");
TestParsing("S00","1e2fm");
TestParsing("S00","1e2m");
TestParsing("S15","1.2.3");
//!!TestParsing("S15","1.2.a");
TestParsing("S00","0oFF,\"A{0oFF}B\"");
TestParsing("S18","0o100");
TestParsing("S18","0o0FF");
TestParsing("S19","0u110000");
TestParsing("S00","0u0");
TestParsing("S00","0uFF");
TestParsing("S00","0u10FFFF");
TestParsing("S19","0u110000");
TestParsing("S19","0u0000000");
TestParsing("S70",".0");
TestParsing("S70",".");
TestParsing("S70",".a");
TestParsing("S15","0u0g");
TestParsing("S00","0u0.a");
TestParsing("S15","0o0g");
TestParsing("S00","0o0.a");
TestParsing("S00","123");
TestParsing("S00","456.789");
TestParsing("S00","3.14m");
TestParsing("S00","0.2");
TestParsing("S00","9e23f");
TestParsing("S00","9e+23f");
TestParsing("S00","9e-23f");
TestParsing("S00","9e0f");
TestParsing("S00","9e-1f");
TestParsing("S00","9e-2f");
TestParsing("S00","5e-3f");
TestParsing("S00","2e-4f");
TestParsing("S00","123.4");
TestParsing("S00","12.34");
TestParsing("S00","1.234");
TestParsing("S00","0.1234");
TestParsing("S00","0.012340");
TestParsing("S00","/a/sha256'FDED'/(/d:)c/e");
TestParsing("S25","/a/b/(q:)c/e");
TestParsing("S26","/(/b:)a");
TestParsing("S20","/a/(/c:)(/d:)b");
TestParsing("S00","/a/b&c");
TestParsing("S00","\"Hello\"");
TestParsing("S00","\"AB\\r\\nCD\"");
TestParsing("S00","0u1");
TestParsing("S00","0u01");
TestParsing("S00","0u01 ");
TestParsing("S00"," 0x1  ");
TestParsing("S00"," 0x01  ");
TestParsing("S00"," 1  ");
TestParsing("S00"," 01  ");
TestParsing("S00","0o1");
TestParsing("S00","0o01");
TestParsing("S00"," 0o1  ");
TestParsing("S00"," <#x#>  0u01   ");
TestParsing("S00"," <#x#>  0u012   <#y#>    ");
TestParsing("S00"," 12.34e-7km  ");
TestParsing("S00"," /a.com/b/c  ");
TestParsing("S00","123","123");
TestParsing("S00","00123","123");

// Identifiers.
TestParsing("S00","a");
TestParsing("S00","awiefwiefjwoiefjwoiejfwoiejfwef");
TestParsing("S00","abc'def'");
TestParsing("S00","abc'0123def,45334$'");
TestParsing("S00","a.b");
TestParsing("S00","a and /b");
TestParsing("S60","a and @b");
TestParsing("S00","a>/b");
TestParsing("S00","/a(/b)");
TestParsing("S00","a=/b");
TestParsing("S00","a.(/c/d:)b");
TestParsing("S00","a.(c:)b");
TestParsing("S23","a.(c)b");
TestParsing("S20","a.+");
TestParsing("S20","a.1");
TestParsing("S77","123 return");
TestParsing("S77","a 1");
TestParsing("S00","(a:)b");
TestParsing("S23","(a:)1");
TestParsing("S00","(a)+1");
TestParsing("S77","or 3");
TestParsing("S00","do:=1");
TestParsing("S70","do:1");
TestParsing("S70","do+1");
TestParsing("S24","operator'abc");
TestParsing("S24","operator'<#'");
TestParsing("S00","operator'<='");
TestParsing("S00","/path/a/b");
TestParsing("S20","/path/7");
TestParsing("S26","/!");
TestParsing("S26","/ab@!");
TestParsing("S00","/an@cd.com");
TestParsing("S00","a.b");
TestParsing("S00"," a  .b   ");
TestParsing("S00"," a. b   ");
TestParsing("S00"," a\n.b  ");
TestParsing("S00"," a  \n   .b    ");
TestParsing("S77","a of:=");
TestParsing("S00"," Tim  ");
TestParsing("S00"," (  Hi   )     ");
TestParsing("S00"," (  Hi   :)     Tim      ");
TestParsing("S80"," (  Hi   \n    )     ");
TestParsing("S80"," (  Hi   \n    :)     Tim      ");
TestParsing("S00","x");
TestParsing("S00"," x  ");
TestParsing("S00","Blah","Blah");
TestParsing("S00","abc'def'","abc'def'");
TestParsing("S00","(1:)ident","(1:)ident");
TestParsing("S00","a.b");
TestParsing("S00"," a  .b   ");
TestParsing("S00","a.(b:)c");
TestParsing("S00"," a  .(   b    :)     c      ");
TestParsing("S20","a.`");
TestParsing("S71","a. `");

// Arrays and lists.
TestParsing("S00","");
TestParsing("S70",";");
TestParsing("S00","1;");
TestParsing("S70","1;;");
TestParsing("S70","1;;2");
TestParsing("S00","1;2");
TestParsing("S00","1;2;");
TestParsing("S70","1;2;;");
TestParsing("S70",";;");
TestParsing("S00","array:\n 1,2;");
TestParsing("S00","array:\n 1,2;\n");
TestParsing("S00","array:\n 1\n 2");
TestParsing("S00","array:\n 1,2");
TestParsing("S00","array:\n 1,2\n");
TestParsing("S70","{");
TestParsing("S00","a;b;c");
TestParsing("S00","a;");
TestParsing("S70","a;;");
TestParsing("S70","a;;b;;c");
TestParsing("S00","1,2");
TestParsing("S00","1;2;");
TestParsing("S00","1;2,3;4");
TestParsing("S00","1\n2");
TestParsing("S00","array{1,2}");
TestParsing("S00","1\n2\nx+y\nblah");
TestParsing("S00","array{1,2},array:\n  1\n  2\n");
TestParsing("S00","1;2;3");
TestParsing("S00"," 1  ,   2    ,     3      ");
TestParsing("S00"," 1  ;   2    ;     3      ");
TestParsing("S00"," 1,2  ;   3,4,5    ; 7,8,9     ");
TestParsing("S00"," (  1   ,    2     )      ");
TestParsing("S00","array{}","()");
TestParsing("S00","array{1}","array{1}");
TestParsing("S00","array{1,2}","1,2");
TestParsing("S00","()","()");
TestParsing("S00","(1)","1");
TestParsing("S00","(1,2)","1,2");
TestParsing("S00","1,2","1,2");
TestParsing("S00","3;4","array{3; 4;}");
TestParsing("S00","1,2;3;4,5","array{1,2; 3; 4,5;}");
TestParsing("S00","(1,2);3;(4,5)","array{1,2; 3; 4,5;}");
TestParsing("S00","1,(2,3),4","1,array{2; 3;},4");
TestParsing("S00","1,(2,3),4","1,(2,3),4");

// Characters.
TestParsing("S31","''");
TestParsing("S00","'''");
TestParsing("S00","'a'");
TestParsing("S30","'\r'");
TestParsing("S00","'\\'");
TestParsing("S00","'''");
TestParsing("S31","'ab'");
TestParsing("S31","'a\r");
TestParsing("S30","'\r\n'");
TestParsing("S00","'\''");
TestParsing("S77","''''");
TestParsing("S00","'a'");
TestParsing("S00"," 'a'  ");
TestParsing("S00","'x'","'x'");
TestParsing("S00","'\\n'","0uA");
TestParsing("S00","'{'","'{'");

// Strings.
TestParsing("S00","\"Hello\"");
TestParsing("S32","\"Hello");
TestParsing("S32","\"Hel\nlo\"");
TestParsing("S00","\"ab\\rd\"");
TestParsing("S34","\"ab\\$cd\"");
TestParsing("S24","operator'ab{0x21}d'");
TestParsing("S00","\"Hello, {Name}. Math {1+2,3,\"x\"}. {x:int=3}.\"");
TestParsing("S00","\"{x:int}\"=\"032\" and x");
TestParsing("S00","\"\\< \\> \\\\ \\r \\n \\t\"");
TestParsing("S00","\"He{0o1}llo\"");
TestParsing("S00","\"He{0o01}llo\"");
TestParsing("S00","\"He{0u12}llo\"");
TestParsing("S00","\"He{0u012}llo\"");
TestParsing("S00","\"He{ 0u012  }llo\"");
TestParsing("S00","\"He{ <#x#>  0u012   <#y#>    }llo\"");
TestParsing("S00","\"He<#xyz#>llo\"");
TestParsing("S00","\"He<#>llo\"");
TestParsing("S00"," \"He<#whoa#>llo\"  ");
TestParsing("S00","\"He{ 1,  2   }llo\"");
TestParsing("S00","\"He{ 1,  2   ;    3     ,      4       }llo\"");
TestParsing("S00","\"ab\\ncd\"","\"ab\\ncd\"");
TestParsing("S00","\"ab\\rcd\"","\"ab\\rcd\"");
TestParsing("S00","\"ab\\r\\ncd\"","\"ab\\r\\ncd\"");
TestParsing("S18","\"A{0o101}B\"");

// Symbols.
TestParsing("S65","a==b");
TestParsing("S68","//a");
TestParsing("S68","a // b");
TestParsing("S00","not x");
TestParsing("S00"," not  x   ;    ");
TestParsing("S00","&x");
TestParsing("S00"," &  x   ");
TestParsing("S00","x^");
TestParsing("S00"," x  ^   ");
TestParsing("S00","[]int");
TestParsing("S00","[3]int");
TestParsing("S00","t:type<[3]int=123");
TestParsing("S00"," [  ]   int    ");
TestParsing("S00"," [  3   ]    int     ");
TestParsing("S00","^1,?1,+1,-1,*1");
TestParsing("S00"," +  int   ");
TestParsing("S00","[]a<b<c");
TestParsing("S00","[]a<b><c");
TestParsing("S00","[]a<b><c>");
//TestParsing("S00","[]{4}");
//TestParsing("S00","[3]{4}");
//TestParsing("S00"," [  ]   {    4     }     ");
//TestParsing("S00"," [  3   ]    {     4      }       ");
//TestParsing("S00"," +  {   1    }     ");
TestParsing("S00","x+1");
TestParsing("S00"," x  +   1    ");
TestParsing("S00"," (  x   )    +     (      1       )        ");
TestParsing("S00","&1","&1");
TestParsing("S00","a=b");
TestParsing("S00"," a  =   b    ");

// Expressions.
TestParsing("S00","1+2*3,+4,-4");
TestParsing("S00","-x*+x,[1]2,[]3");
TestParsing("S00","1*2+3*4,1+2+3,\"Hi\",a and b,as[2],c<d,0x123ABC");
TestParsing("S00","0,1,-a,+b,?^t,<#a#>[1]2,3[4]:=5,(1,2),:t,/xs,not 123,/a/b,/a@b/c");
TestParsing("S00","operator'+'(1,2),prefix'?'[int]");
TestParsing("S00","1,&1,&x:int");
TestParsing("S00","1+2-3*4/5,123{m/s}");
TestParsing("S00","1,&1,&x:int");
TestParsing("S00","x:int,y:int where x=10,y>10,z=10");
TestParsing("S00","x:int,y:int where x<10,y>10,z<10");
TestParsing("S00","/bob-smith@my-host.com,/epic,\"{/a}\"");
TestParsing("S00","a<b&c");
TestParsing("S00","Print of x+1");
TestParsing("S00","Print of {x+1}");
TestParsing("S00","'x',0u1234<#,[a]{b,c}#>");
TestParsing("S00","f(x&y:int):int");
TestParsing("S00","1+2+3","1+2+3");
TestParsing("S00","(1+2)+3","1+2+3");
TestParsing("S00","1+(2+3)","1+(2+3)");
TestParsing("S00","(1+2)*(3+4)","(1+2)*(3+4)");
TestParsing("S00","1*2+3*4","1*2+3*4");
TestParsing("S00","x?^","x?^");
TestParsing("S00","((x?)^)","x?^");
TestParsing("S00","(a?)+(b?)","a?+b?");
TestParsing("S00","(a?+b)?","(a?+b)?");
TestParsing("S00","-x","-x");
TestParsing("S00","--++--++123","--++--++123");
TestParsing("S00","-1+-2*3","-1+-2*3");
TestParsing("S00","(-1)+((-2)*3)","-1+-2*3");
TestParsing("S00","-((1+2)*3)","-((1+2)*3)");
TestParsing("S00","not not not 3","not not not 3");
TestParsing("S00","....not not-3","....not not-3");
TestParsing("S00","not 1 and not 2","not 1 and not 2");
TestParsing("S00","(not 1) and (not 2)","not 1 and not 2");
TestParsing("S00","not(1 and not 2)","not(1 and not 2)");
TestParsing("S00","0 and 1","0 and 1");
TestParsing("S00","not 0","not 0");

TestParsing("S00","[][3][]4","[][3][]4");
TestParsing("S00","[1][2,3][4;5][2,3;4,5]7","[1][2,3][array{4; 5;}][array{2,3; 4,5;}]7");
TestParsing("S00",":t",":t");
TestParsing("S00",":-t",":-t");
TestParsing("S60","not :-t","not :-t");
TestParsing("S60",":not t");
TestParsing("S00",":(not t)",":(not t)");
TestParsing("S00","-(not t)","-(not t)");
TestParsing("S00","not a=b","not a=b");
TestParsing("S00","?a[]","?a[]");
TestParsing("S00","(?a)[]","(?a)[]");
TestParsing("S00","?(a[])","?a[]");
TestParsing("S00","?a{}","?a{}");
TestParsing("S00","(?a){}","(?a){}");
TestParsing("S00","?(a{})","?a{}");
TestParsing("S00","?a?","?a?");
TestParsing("S00","(?a)?","(?a)?");
TestParsing("S00","?(a?)","?a?");
TestParsing("S00","(not a)=b","(not a)=b");
TestParsing("S00","not a>b<c","not a>b<c");
TestParsing("S00","not ((a>b)<c)","not a>b<c");
TestParsing("S00","((not a)>b)<c","(not a)>b<c");
TestParsing("S00","not a=b","not a=b");
TestParsing("S00","(not a)=b","(not a)=b");
TestParsing("S00","not (a=b)","not a=b");
TestParsing("S00"," x  in   2    ");
TestParsing("S00","&&b");
TestParsing("S70","||b");
TestParsing("S77","a!");
TestParsing("S62","a&&b");
TestParsing("S62","a||b");
TestParsing("S62","!a");

// Definitions.
TestParsing("S00","x:int");
TestParsing("S00","x:int:=3");
TestParsing("S00","x:int=3");
TestParsing("S00","x:=1");
TestParsing("S00","x=>1");
TestParsing("S00"," x  :=   1    ");
TestParsing("S00"," x  =>   1    ");
TestParsing("S00","x:={1}");
TestParsing("S00","x=>{1}");
TestParsing("S00"," x  :=   {    1     }      ");
TestParsing("S00"," x  =>   {    1     }      ");
TestParsing("S00","x:=\n 1");
TestParsing("S00","x=>\n 1");
TestParsing("S00"," x  :=   \n     1     ");
TestParsing("S00"," x  =>   \n     1     ");
TestParsing("S00","x:=\n 1\n 2");
TestParsing("S00","x:=\n 1\n 2");
TestParsing("S00"," x  :=   \n     1     \n       2       ");
TestParsing("S00"," x  =>   \n     1     \n       2       ");
TestParsing("S00",":3");
TestParsing("S00","::3");
TestParsing("S00"," :  3   ");
TestParsing("S00"," :  :   3    ");
TestParsing("S00",":int=3");
TestParsing("S00"," :  int   =    3     ");
TestParsing("S00","x:int=3");
TestParsing("S00"," x  :   int    =     3      ");
TestParsing("S00",":a:b");
TestParsing("S00","x:nat:int");
TestParsing("S00","x :  nat   :    int     ");
TestParsing("S00","x:nat:int=4");
TestParsing("S00"," x  :   nat    :     int      =       6        ");
TestParsing("S00",":nat:int=4");
TestParsing("S00"," :  nat   :    int     =      6       ");
TestParsing("S00","x is 3");
TestParsing("S00","x is(3)");
TestParsing("S00","x is  3   ");
TestParsing("S00","x\nis 3");
TestParsing("S00"," x  \n   is    3");
TestParsing("S00","1=>2","1=>2");
TestParsing("S00","1=>{2;3;}","1=>{2; 3;}");
TestParsing("S00","(1=>2)=>(3=>4)","(1=>2)=>3=>4");
TestParsing("S00","1:=2","1:=2");
TestParsing("S00","1:={2;3;}","1:={2; 3;}");
TestParsing("S00","(1:=2):=(3:=4)","(1:=2):=3:=4");
TestParsing("S00","(1:=2)=>3","1:=2=>3");
TestParsing("S00","1:=(2=>3)","1:=(2=>3)");
TestParsing("S00","1=>(2:=3)","1=>2:=3");
TestParsing("S00","(1=>2):=3","(1=>2):=3");
TestParsing("S00","(1,2)=>(3,4)","(1,2)=>(3,4)");
TestParsing("S00","x:=3","x:=3");
TestParsing("S00","x:=y:=4","x:=y:=4");
TestParsing("S00","(x:=y):=4","(x:=y):=4");
TestParsing("S00","x:=(y:=4)","x:=y:=4");
TestParsing("S00",":nat",":nat");
TestParsing("S00",":nat=3",":nat:=3");
TestParsing("S00",":nat=3=4",":nat:=3=4");
TestParsing("S00",":nat=(3=4)",":nat:=3=4");
TestParsing("S00","x:nat","x:nat");
TestParsing("S00","x:nat=3","x:nat:=3");
TestParsing("S00","x:nat=3=4","x:nat:=3=4");
TestParsing("S00","(x:nat=3)=4","(x:nat:=3)=4");
TestParsing("S00","x:nat=(3=4)","x:nat:=3=4");
TestParsing("S00","x:nat<3","x:nat<3");
TestParsing("S00","x:nat<3:=4","x:nat<3:=4");
TestParsing("S00","x:nat<3=4","x:nat<3:=4");
TestParsing("S00","(x:nat<3)=4","(x:nat<3)=4");
TestParsing("S00","x:(nat<3)=4","x:(nat<3):=4");
TestParsing("S00","x:nat<(3=4)","x:nat<(3=4)");
TestParsing("S00","a=>:b","a=>:b");
TestParsing("S00",":a=>:b",":a=>:b");
TestParsing("S00","1+(:b)","1+(:b)");
TestParsing("S00","a and (:b)","a and(:b)");
TestParsing("S00","x:=(:t)+1","x:=(:t)+1");
TestParsing("S00","x:(t:u)","x:(t:u)");
TestParsing("S00","x:(t:(u=v))","x:(t:(u=v))");
TestParsing("S00","x:?t?","x:?t?");
TestParsing("S00","x::t","x::t");
TestParsing("S00","x:(:t)","x::t");
TestParsing("S00","(:nat=3):=4","(:nat:=3):=4");
TestParsing("S00","x:t:u","x:t:u");
TestParsing("S00","(x:t:u)","x:t:u");
TestParsing("S00","(x:t):u","(x:t):u");
TestParsing("S00","x:(t:u)","x:(t:u)");
TestParsing("S00","f(x:t:u)","f(x:t:u)");
TestParsing("S00","+(x:t:u)","+(x:t:u)");
TestParsing("S00","(x:t:u)+(y:v:w)","(x:t:u)+(y:v:w)");
TestParsing("S00","x:=((:t):=:u)","x:t:u");
TestParsing("S00","((x:t):u)=v","((x:t):u)=v");
TestParsing("S00","(x:(t:u))=v","(x:(t:u))=v");
TestParsing("S00","(x:t:u)=v","(x:t:u)=v");
TestParsing("S00","x:t:u=v","x:t:u:=v");
TestParsing("S00","x:::t::u:v=w","x:::t::u:v:=w");
TestParsing("S00"," x  :   t    ,     x      :       :        t         ");
TestParsing("S00","a of b=>c","a(b=>c)");
TestParsing("S00","(a of b)=>c","a(b)=>c");
TestParsing("S00","a of (b=>c)","a(b=>c)");
TestParsing("S00","1:t");
TestParsing("S00","block:={1; 2;}");
TestParsing("S00","x:=123");
TestParsing("S00","a<fancy>,a<private>:=c");
TestParsing("S00","f(x:int):int,f():int:={1; 2;},f():={1; 2;}");
TestParsing("S00","x:nat<3","x:nat<3");

// Attributes.
TestParsing("S00","@attr\nx:=3");
TestParsing("S00","@attr x:=3");
TestParsing("S00","x:int @attr");
TestParsing("S71","@");
TestParsing("S00","@attr\nx:=1");
TestParsing("S00","@a@b\nx:=1");
TestParsing("S00"," @ a @ b \n x := 1 ");
TestParsing("S00","@attr x:=1");
TestParsing("S00","@attr{} a");
TestParsing("S00","@attr{a:=1}\nx:=1");
TestParsing("S00","@attr{a:=1}x:=1");
TestParsing("S00","@attr(a:=1){b:=1}\nx:=1");
TestParsing("S67","@attr");
TestParsing("S67","@path/oops");
TestParsing("S67","@/path/oops");
TestParsing("S00","@/path/oops\nx:=3");
TestParsing("S00","@a @b x:int");
TestParsing("S67","@a @b -x");
TestParsing("S00","@a b");
TestParsing("S00"," @  a   b    ");
TestParsing("S00"," @a<b<c>> d");
TestParsing("S00"," @a<b> c");
TestParsing("S00"," @a(b) c");
TestParsing("S67"," @a");
TestParsing("S61"," @a<b");
TestParsing("S67"," @a+b");
TestParsing("S82","a(b:)c");
TestParsing("S82","a(b)(c:)d");
TestParsing("S00","@a(b:)c");
TestParsing("S00","@a(b)(c:)d");
TestParsing("S00","@a(b:)c+1");
TestParsing("S82"," a  (   b    :)     c      ");
TestParsing("S82"," a  (   b    )     (      c       :)        d");
TestParsing("S00"," @  a   (    b     :)      c       ");
TestParsing("S00"," @  a   (    b     )      (       c        :)         d          ");
TestParsing("S00"," @  a   (    b     :)       c        +         1          ");

// Inequalities and specifiers.
TestParsing("S00","1<2<3");
TestParsing("S00","1<=2<=3");
TestParsing("S00","1>2<3");
TestParsing("S00","2<=3=4");
TestParsing("S00","2>=3=4");
TestParsing("S00","a+b>c+d<e+f");
TestParsing("S00","1>=2<=3");
TestParsing("S61","1<=2>=3");
TestParsing("S00","x>3:int");
TestParsing("S00","1=2<>3");
TestParsing("S00","1=2:3");
TestParsing("S00","1=2<3");
TestParsing("S00","1=2<=3");
TestParsing("S00",":nat<7,:int<a>->int");
TestParsing("S00","a<b><c>");
TestParsing("S00","a<b><e><f>:=g");
TestParsing("S00","1<2<3>");
TestParsing("S00","1=2<3>");
TestParsing("S00","1=2+3");
TestParsing("S00","1=2 and 3");
TestParsing("S00","a<b>->c");
TestParsing("S00","a<b>->c<d>->e");
TestParsing("S00","a->b<c>->d");
TestParsing("S00","a->b<c>");
TestParsing("S00","a<b>->c<d>");
TestParsing("S00","a->b,a<b>->c,a<b>->c<d>,a<b><c>->d<e><f>");
TestParsing("S60","1+not 2");
TestParsing("S71","[a]\nnot 1");
TestParsing("S00","a:=1+[b]c");
TestParsing("S60","1+not 2");
TestParsing("S00","a<b><c>");
TestParsing("S00","a<b+c>");
TestParsing("S77","a<b+c>e");
TestParsing("S71","a<b=c>");
TestParsing("S00","1 with<2>");
TestParsing("S78","1 with 2");
TestParsing("S79","1 with<2");
TestParsing("S00","1 with<2><3>+4");
TestParsing("S00","m(a)with<c>{d}");
TestParsing("S00","m(a)<b>with<c>{d}");
TestParsing("S00","a=b<c<>d<>e");
TestParsing("S00","a with<b>");
TestParsing("S00"," a  with   <    b     >      ");
TestParsing("S00","a\nwith<b>");
TestParsing("S00"," a  \n   with    <     b      >       ");
TestParsing("S00","a with<b><c>");
TestParsing("S00"," a  <   b    >     with       <        c         >          ");
TestParsing("S00"," a  with   <    b     >      ");
TestParsing("S00"," a  with   <    b     >       <       c         >          ");
TestParsing("S00"," a  <   b    >     with      <       c        >         ");
TestParsing("S00","f<a>{x}");
TestParsing("S00"," f  <   a    >     {      x       }        ");
TestParsing("S00","f<a>{x}<b>+c<d");
TestParsing("S00","f(a){b}");
TestParsing("S00","f<a>(b)<c>{d}");
TestParsing("S00"," f  (   a    )     {      b       }        ");
TestParsing("S00"," f  <   a    >     (      b       )        <         c          >           {            d            }             ");
TestParsing("S00","a<b>");
TestParsing("S00","a<b><c>");
TestParsing("S00"," a  <   b    >     <      c       >        ");
TestParsing("S00","f<1>","f<1>");
TestParsing("S00","f<1><2>","f<1><2>");
TestParsing("S00","f<1>(2)<3>[4]","f<1>(2)<3>[4]");
TestParsing("S00","f(1)<2>[3]<4>","f(1)<2>[3]<4>");
TestParsing("S00","a<b<c=>2","a<b<c=>2");
TestParsing("S00","a<=b<=c","a<=b<=c");
TestParsing("S00","(a<=b)<=c","(a<=b)<=c");
TestParsing("S00","a<=(b<=c)","a<=b<=c");
TestParsing("S00","a<b<c","a<b<c");
TestParsing("S00","(a<b)<c","(a<b)<c");
TestParsing("S00","a<(b<c)","a<b<c");
TestParsing("S00","a>b>c","a>b>c");
TestParsing("S00","(a>b)>c","(a>b)>c");
TestParsing("S00","a>(b>c)","a>b>c");
TestParsing("S00","x=a>b>c<=d<=e<>f","x=a>b>c<=d<=e<>f");
TestParsing("S00","(x=(a>(b>c)<=(d<=e)))<>f","(x=a>b>c<=d<=e)<>f");
TestParsing("S00","(((((x=a)>b)>c)<=d)<=e)<>f","(((x=a)>b)>c<=d)<=e<>f");
TestParsing("S00","x=a>b>c<d<e<>f","x=a>b>c<d<e<>f");
TestParsing("S00","(x=(a>(b>c)<(d<e)))<>f","(x=a>b>c<d<e)<>f");
TestParsing("S00","(((((x=a)>b)>c)<d)<e)<>f","(((x=a)>b)>c<d)<e<>f");
TestParsing("S00","1=2<>3=4<>5","1=2<>3=4<>5");
TestParsing("S00","1=(2<>(3=(4<>5)))","1=2<>(3=4<>5)");
TestParsing("S00","(((1=2)<>3)=4)<>5","((1=2)<>3=4)<>5");
TestParsing("S00","a>b<(c>d)","a>b<(c>d)");
TestParsing("S00","a>(b<(c>d))","a>(b<(c>d))");
TestParsing("S00","(a<b)>(c<d)","(a<b)>(c<d)");
TestParsing("S00","(a>b)<(c>d)","a>b<(c>d)");
TestParsing("S00","a^<b^<c^","a^<b^<c^");
TestParsing("S00","-a<-b<-c","-a<-b<-c");
TestParsing("S00","(-a)<((-b)<-c)","-a<-b<-c");
TestParsing("S00","((-a)<-b)<-c","(-a<-b)<-c");
TestParsing("S00","-(a<-(b<-c))","-(a<-(b<-c))");
TestParsing("S00","a and b<c+d<-e<f and g","a and b<c+d<-e<f and g");
TestParsing("S00","a and (b<(c+d<((-e)<f))) and g","a and b<c+d<-e<f and g");
TestParsing("S61","1<>2<3");
TestParsing("S61","1<>2>3");
TestParsing("S00","b<a>");
TestParsing("S00","a.c<b>");
TestParsing("S00"," a  =   b    <     c      <>       d        <>         e          ");
TestParsing("S00","1<2<=3","1<2<=3");
TestParsing("S00","1<=2<3<=4<5","1<=2<3<=4<5");
TestParsing("S61","a<=b>=c");
TestParsing("S00"," a < b > = c ");
TestParsing("S00"," a < b >= c ");
TestParsing("S00","a<b>=c");
TestParsing("S00","(a<b)>=c","(a<b)>=c");
TestParsing("S00","a<(b>=c)","a<(b>=c)");
TestParsing("S00","-a<-b<-c","-a<-b<-c");
TestParsing("S00"," -  a   <    -     b      <       -        c         ");
TestParsing("S00","(-a)<b","-a<b");
TestParsing("S00","-(a<b)","-(a<b)");
TestParsing("S00","-(a<b>)","-a<b>");
TestParsing("S00","(-a)<b>","(-a)<b>");
TestParsing("S00","Print of  x  +   1    <     2      ");
TestParsing("S00","Print of  x  +   1    is     2      ");

// Macros.
TestParsing("S71","for(x:xs)do\r");
TestParsing("S71","for(x:xs)do");
TestParsing("S71","for(x:xs)do,2");
TestParsing("S00","for(x:xs)do:");
TestParsing("S00","for(x:xs)do:\r");
TestParsing("S00","for(x:xs)do:\r2");
TestParsing("S71","for(x:xs)do:;2");
TestParsing("S77","m()do{1}do{2}");
TestParsing("S77","m()then{1}");
TestParsing("S77","m()do{1}then{2}");
TestParsing("S00","m{}");
TestParsing("S00","m(){}");
TestParsing("S00","m(). a");
TestParsing("S00","m() do a ");
TestParsing("S00","m() in a ");
TestParsing("S00","m() + a ");
TestParsing("S00","let(x:int). x+1");
TestParsing("S00","let(x:int).x");
TestParsing("S20","let(x:int).\n x+1");
TestParsing("S00","let(x:int):\n x+1");
TestParsing("S00","for(x:xs) do wtf");
TestParsing("S00","for(x:xs)do:\r 1\r 2","for(x:xs){1; 2;}");
TestParsing("S00","for(x:xs)do:\r1","array{for(x:xs){}; 1;}");
TestParsing("S77","mymacro do{}");
TestParsing("S77","if(a)then{b}do{c}until{d}else{e}");
TestParsing("S77","if(a)then{b}until d");
TestParsing("S00","bag{}");
TestParsing("S00","bag{1}");
TestParsing("S00","bag{1,2}");
TestParsing("S77","for(a) until b");
TestParsing("S00","for{a} until { b } ");
TestParsing("S00","for{a} until b");
TestParsing("S00","for(a){b} until c");
TestParsing("S00","for(a)do{b} until c");
TestParsing("S00","for(a) do  b   until    c     ");
TestParsing("S00","for{a} do  b   until    c     ");
TestParsing("S77","for(a) do b do c");
TestParsing("S00","for(a) do if(b) then for(c) do d until f");
TestParsing("S00","for(a) do if(b) then for(c) do d else e until f");
TestParsing("S00","for(x:xs)<par> do Print(x)");
TestParsing("S00","m(a)<b>{c},m(a)<b><c>");
TestParsing("S00","tail(xs:[n]t where n:nat>0, t:type):=xs[n-1]");
TestParsing("S00","let(x:=3){x+1}");
TestParsing("S00","let{x:=3}do{x+1}");
TestParsing("S00","let{x:=3}do x+1");
TestParsing("S00","for(a:b,c){d*e,f+g}");
TestParsing("S00","a:\n b\n d\ndo:\n d\n e\nblah");
TestParsing("S00","a:\n b\n d\nuntil:\n d\n e\nblah");
TestParsing("S00","a:\n b\n\tc\nblah");
TestParsing("S89"," a:\n  b\n\t c\nblah");
TestParsing("S00","x where x:=3");
TestParsing("S70","x\nwhere x:=3");
TestParsing("S00","a{b},(c){d}");
TestParsing("S00","(1+2)(3) do 4");
TestParsing("S00","(1+2)(3) do 4");
TestParsing("S00","let(x:=3){x+1},let{x:=3}do{x+1}");
TestParsing("S00","macro\n{\n1\n2\n{3}}\n");
TestParsing("S71","m in\n 1\n 2");
TestParsing("S00","f{x}");
TestParsing("S00"," f  {   x    }     ");
TestParsing("S00"," f  {   x    ,     y      ;       z        ,         w          }           ");
TestParsing("S00","f(a)do{b}");
TestParsing("S00"," f  (   a    )       do        {         b          }           ");
TestParsing("S00","f<a>(b)<c>do{e}");
TestParsing("S00"," f  <   a    >     (      b       )        <         c          >           do            {             e              }               ");
TestParsing("S00","f(a)do b");
TestParsing("S00"," f  (   a    )     do      b      ");
TestParsing("S00","f(a)do. b");
TestParsing("S00"," f  (   a    )      do.      b      ");
TestParsing("S00","m{a}until{b}");
TestParsing("S00","m(a){b}until{c}");
TestParsing("S00","m. a");
TestParsing("S00"," m.  a   ");
TestParsing("S00","m(a). b");
TestParsing("S00"," m  (   a    ).     b     ");
TestParsing("S00","m:\n a");
TestParsing("S00","m:\n a\n b");
TestParsing("S00","m:\n a\nc");
TestParsing("S00","m:\n a\n b\nc");
TestParsing("S20","m.\n a");
TestParsing("S20","m.\n a\n b");
TestParsing("S20","m.\n a\nc");
TestParsing("S20","m.\n a\n b\nc");
TestParsing("S00","for(x in 1 to 100) do Print(x)");
TestParsing("S00"," m  {   a    }     <      b       >        +         c          ");
TestParsing("S00"," a:\n  b\n  #c");
TestParsing("S89"," a:\n  b\n\t #c");
TestParsing("S00"," a\n  { \n   a \n  } \n");
TestParsing("S00","a: \n b\nc");
TestParsing("S71","a. \n b\nc");
TestParsing("S00","m{a}<b>{}");
TestParsing("S00","m{a}<b><c>do{}");
TestParsing("S00"," m  {   a    }     <      b       >        <         c          >           do            d             ");
TestParsing("S00","a\n { \n b\n c \n } \n ");
TestParsing("S00","<m{a}\n ;a>");
//!!TestParsing("S00","<m(a)\n ;a>");
//!!TestParsing("S00","<m<a>\n ;a>");
//!!TestParsing("S00","<m<a>(b)\n ;a>");
TestParsing("S00","<m(a)<b>\n ;a>");
TestParsing("S00"," m(a) <  b   >    ");
TestParsing("S00"," m(a) <  b   and 7");
TestParsing("S00"," m(a) <  b   ");

// Bad or missing expression, block, keyword.
TestParsing("S70","]");
TestParsing("S70","\x81");
TestParsing("S71","if(a){b}else");
TestParsing("S70","]");
TestParsing("S71","[attr]");
TestParsing("S77","ab cd");
TestParsing("S00","(/b)/a");
TestParsing("S00","[2]int");
TestParsing("S00","a[b]");
TestParsing("S00","\"ab\\r\\n\\t\\{\\}\"");

// Expression grouping.
TestParsing("S81","(\x81");
TestParsing("S81","(1,2]");
TestParsing("S80","abc(");
TestParsing("S80","abc(def");
TestParsing("S82","f(1,2]");
TestParsing("S83","a[b)");
TestParsing("S85","[2)int");
TestParsing("S84","f{1,2]");
TestParsing("S84","m{a}do{b]");
TestParsing("S84","x:int=>{2,3]");
TestParsing("S86","\"ab{2]");
TestParsing("S86","\"ab{2,$");
TestParsing("S86","\"abc{d]\"");
TestParsing("S88","array:\n 3\n )");

// Prefix operators.
TestParsing("S00","[]int");
TestParsing("S00","[n]char");
//TestParsing("S00","[]{'x'}");
//TestParsing("S00","[]{'x'|'y'}");
//TestParsing("S00","[n]{'x'|'y'}");

// Units.
TestParsing("S00","1m + 2cm");
TestParsing("S00","1.2m,3.14ha");

// Calls.
TestParsing("S00","f()","f()");
TestParsing("S00","f(1)","f(1)");
TestParsing("S00","f(1;)","f(1)");
TestParsing("S00","f(1,2)","f(1,2)");
TestParsing("S00","f(array{1})","f(array{1})");
TestParsing("S00","f(())","f()");
TestParsing("S00","f((1))","f(1)");
TestParsing("S00","f((1,2))","f(1,2)");
TestParsing("S00","f(a)(b)","f(a)(b)");
TestParsing("S00","f[1]","f[1]");
TestParsing("S00","f[1,2]","f[1,2]");
TestParsing("S00","f[1][2]","f[1][2]");
TestParsing("S00","f(1)[2](3)[4]","f(1)[2](3)[4]");
TestParsing("S00","f[1](2)[3](4)","f[1](2)[3](4)");
TestParsing("S00","a[b]");
TestParsing("S00"," a  [   b    ]     ");
TestParsing("S00","a[b,c;d]");
TestParsing("S00"," a  [   b    ,     c      ;       d        ]         ");
TestParsing("S00"," a  at   b    ");
TestParsing("S00"," a  at   (    b     ,      c       )        ,        d          ");
TestParsing("S00","f(x)");
TestParsing("S00"," f  (   x    )     ");
TestParsing("S00"," f  (   x    ,     y      ;       z        ,         w          )           ");
TestParsing("S00"," f  of   g    ");
TestParsing("S00"," f  of   {    g     }      ");
TestParsing("S00"," f  of   (    g     ,      6       )        ");
TestParsing("S00"," f  of   {    g     ,      6       }        ");
TestParsing("S00"," 1  to   2    ");
TestParsing("S71","f of");
TestParsing("S71","f of\n");
TestParsing("S71","f of\n 3");
TestParsing("S71","f of\n3");
TestParsing("S00","f of:");
TestParsing("S00","f of:\n");
TestParsing("S00","f of:\n 3");
TestParsing("S00","f of:\n3");
TestParsing("S00","f of. 3");
TestParsing("S71","f of. \n3");
TestParsing("S71","f of.\n3");
TestParsing("S71","f of. \n3 ");
TestParsing("S71","f of.\n3 ");

// Logic.
TestParsing("S00","not 123");
TestParsing("S00","not 1=2");
TestParsing("S00","[1]2->*3->+4");
TestParsing("S00","3+4<-5");
TestParsing("S00","1+2<3+4<-5");
TestParsing("S00","a or b and c or not ddd");
TestParsing("S00","not x,f(1,2),f(1){2}");
TestParsing("S00","1..2,x:=0..9,for(x:=0..9,y:='A'..'Z') {x+y}");
TestParsing("S00","1=2");
TestParsing("S00","x:int | a:=x+1 | x<>3");
TestParsing("S00","1 or 2 and not 3 and 4 or not 5");
TestParsing("S00","(a) and (b)");
TestParsing("S00"," not  123   ");
TestParsing("S00"," not  123   ");
TestParsing("S00"," a  and   b    or     c      ");

// Array dot dot.
TestParsing("S00","1,..(2,3),..xs:[]int,..:arr,..(xs:=array{1,2}),4");

// Macro management.
TestParsing("S00","capture{x+1},code{x,&x,&&x}");

// Identifiers.
TestParsing("S00","a.b,operator'+',operator'+'<e>,a.operator'*',a.b<c>,a.operator'-='<b>");
TestParsing("S00","(a:)andy");

// Unicode.
TestParsing("S00",u8"\"ßädÄ55 2©3ಅ4𠜎 (ಠ_ಠ) ¯\\\\_(ツ)_/¯\"");

// Keywords in strange places.
TestParsing("S77","(a)do");
TestParsing("S00","a.do:=3");
TestParsing("S00","a.do+3");
TestParsing("S00","a.(b:)do:=3");
TestParsing("S00","a.(b:)do+3");
TestParsing("S77","123 do 7");
TestParsing("S00","note");
TestParsing("S31","not'abc'");
TestParsing("S76","if'abc'");
TestParsing("S00","or:=3");
TestParsing("S00","do:=3");
TestParsing("S00","if:=1,then:=3,else:=5,try:=123");
TestParsing("S00","not:=1");
TestParsing("S00","at,of,to,and,or,while,when,over");
TestParsing("S70","where");

// Strings.
TestParsing("S00","\"Hello \\r \\n \\t \"");
TestParsing("S34","\"Hello \\c \\u \\w \"");

// If.
TestParsing("S77","if()then{1}then{2}");
TestParsing("S76","if()do{1}");
TestParsing("S77","if()then{1}do{2}");
TestParsing("S76","if()<1>{2}");
TestParsing("S00","if(x:=3){x+1}else{x-1}");
TestParsing("S00","if(x:=3)then{x+1}else{x-1}");
TestParsing("S00","if(x:=3) then x+1 else x-1");
TestParsing("S00","if(1){2}else{3}");
TestParsing("S00","if:=2");
TestParsing("S00","at:=2");
TestParsing("S00","break:=2,catch:=2,continue:=2,else:=2,if:=2,do:=2,is:=2,not:=2,of:=2,return:=2,then:=2,until:=2,where:=2,with:=2,yield:=2");
TestParsing("S00","if(1){2}");
TestParsing("S76","if is 2");
TestParsing("S76","if not 2");
TestParsing("S00","if{1} then {2}");
TestParsing("S00","if{1} then {2} else {3}");
TestParsing("S00","if(a){b}else if(c){d}+1",  "if(a){b}else{if(c){d}}+1");
TestParsing("S00","(if(a){b}else if(c){d})+1","if(a){b}else{if(c){d}}+1");
TestParsing("S00","if(a){b}else (if(c){d})+1","if(a){b}else{if(c){d}+1}");
TestParsing("S00","a{}<b","a{}<b");
TestParsing("S00","a{}<b<c","a{}<b<c");
TestParsing("S00","a{}<b{}","a{}<b{}");
TestParsing("S00","a{}<b{}<c","a{}<b{}<c");
TestParsing("S00","a{}<b{}<c{}","a{}<b{}<c{}");
TestParsing("S00","if(a){b}else if(c){d}<1",  "if(a){b}else{if(c){d}}<1");
TestParsing("S00","(if(a){b}else if(c){d})<1","if(a){b}else{if(c){d}}<1");
TestParsing("S00","if(a){b}else (if(c){d})<1","if(a){b}else{if(c){d}<1}");
TestParsing("S00","a{}<b{}<c{}","a{}<b{}<c{}");
TestParsing("S00"," a  +   b    <     c      +       d        <        e          +           f            ");
TestParsing("S00","if(a){b}else if(c){d}<1>",  "if(a){b}else{if(c){d}}<1>");
TestParsing("S00","(if(a){b}else if(c){d})<1>","if(a){b}else{if(c){d}}<1>");
TestParsing("S00","if(a){b}else (if(c){d})<1>","if(a){b}else{if(c){d}<1>}");
TestParsing("S00","if(a){b}else{c}");
TestParsing("S00"," if  (   a    )     {      b       }        else{         c          }           ");
TestParsing("S00","if(a) then b else c");
TestParsing("S00"," if  (   a    )     then      b       else        c         ");
TestParsing("S00","if{a}else{b}{c}");
TestParsing("S00","if{a}else{b}{c}do{d}");
TestParsing("S00","if{a}else{b}{c}until{d}");
TestParsing("S77","if{a}else{b}{c}else{d}");
TestParsing("S00","if{a}else  if   {b}    ");
TestParsing("S00","if(a)\nthen b");
TestParsing("S76","if");
TestParsing("S00","if(a){b}else if{a}<b><1");

// Catch.
TestParsing("S70","catch");
TestParsing("S77","1 catch");
TestParsing("S76","m{a} catch 2");
TestParsing("S00","m{a} catch{2}");
TestParsing("S00","m{a} catch(2){3}");
TestParsing("S76","try{a}catch(123)");
TestParsing("S00","try{a}catch(b){c}catch{d}");
TestParsing("S00","m{a} catch{b} until c");
TestParsing("S77","m{a} until c catch{b}");
TestParsing("S00","m{a} catch(x:int) do x+1");
TestParsing("S00","m{a} catch(x:int) do  x   <    7     ");
TestParsing("S00","try:\n a\ncatch:\n 123");
TestParsing("S00"," try: \n  abc \n   def  \ncatch:\n  x:int   \ndo: \n  x  +   1    ");

// Where.
TestParsing("S00","1 where{2}","1 where{2}");
TestParsing("S00","1+2 where 3+4","1+2 where{3+4}");
TestParsing("S00","1,2 where 3,4","1,2 where{3,4}");
TestParsing("S00","1,2 where 3,4 where 5,6","1,2 where{3,4 where{5,6}}");
TestParsing("S00","1,2 where 3,(4 where 5,6)","1,2 where{3,4 where{5,6}}");
TestParsing("S00","1,(2 where 3),4","1,2 where{3},4");
TestParsing("S00","a where b where c","a where{b where{c}}");
TestParsing("S00","a where (b where c)","a where{b where{c}}");
TestParsing("S00","(a where b) where c","(a where{b})where{c}");
TestParsing("S00","1 where:\n b\n c\nd");
TestParsing("S70"," where  :\n  b   \n  c    \nd     ");
TestParsing("S00","1 where. b");
TestParsing("S00","1 where.  b   ");
TestParsing("S70"," 1  \n   where    4     ");
TestParsing("S71","1 where.\n b\n c\nd");
TestParsing("S70"," where  .\n  b   \n  c    \nd     ");

// Macro specifiers versus identifier qualifiers.
TestParsing("S00","for<par>(x:xs){x}");
TestParsing("S00","(/Verse.org/Verse:)for(x:xs){x}");
TestParsing("S00","if(1){2}else if(3){4}else{5}");
TestParsing("S00","if(a){b}else{if(c){d} else{e}}");
TestParsing("S00","if(a){\n Print(a)\n}\nelse{\n Print(b)\n}");
TestParsing("S00","if(a):\n Print(a)\nelse:\n Print(b)\n");
TestParsing("S00","if(a):\n Print(a)\nelse if:\n Print(b)\nthen:\n Print(c)");
TestParsing("S00","\"Angle is {ArcCos(x)}\"");
TestParsing("S00","\"Angle is {ArcCos(x)}, big if true!\"");
TestParsing("S00","Colors:=enum{Red,Green,Blue}");
TestParsing("S00","Colors:=enum\n{\n Red,\n Green,\n Blue\n}");
TestParsing("S76","if(1)else{2}");
TestParsing("S76","if do 1 else{2}");
TestParsing("S00","if. 1 else{2}");

// More.
TestParsing("S00","a,a?,a??,a^,a^^,a?^,a^?");
TestParsing("S00","Fac(x:nat):int<upon(known[x])>=x*Fac[x-1] or 0");

// Macro keywords.
TestParsing("S00","function{x:int} do :int=x+1");

// Return.
TestParsing("S00","return; return 123; yield 4; array{continue; break};");
TestParsing("S00","f():=return 123");
TestParsing("S00","f():=\n return 123");
TestParsing("S00","f[]:int:=return 1");
TestParsing("S00",":int=a=b");
TestParsing("S00",":int=a=b and c=d or e=f and g=h");
TestParsing("S00",":int=return 1");
TestParsing("S00","f[]:int=return 1");
TestParsing("S60","1+return");
TestParsing("S00","return");
TestParsing("S00"," return  ;   ");
TestParsing("S00","return(3)");
TestParsing("S00","return 3");
TestParsing("S00"," return  3   ;    ");
TestParsing("S00","return","return{}");
TestParsing("S00"," return  3    ","return 3");
TestParsing("S00","return{3}","return 3");
TestParsing("S00","return 3,4","return 3,4");
TestParsing("S00","return{3,4}","return{3,4}");
TestParsing("S00"," (  return   )    ");

// Infix identifiers.
TestParsing("S00","dot(a,b) + cross(c,d)");

// Strings and comments.
TestParsing("S00","\"<>\"");
TestParsing("S00","\"<##>\"");
TestParsing("S00","\"<#cmt#>\"");
TestParsing("S04","\"<#\"");
TestParsing("S05","\"#>\"");
TestParsing("S00","\"<#>\"");

// Printing.
TestParsing("S00","123 where 4,5");
TestParsing("S00","a=>b");
TestParsing("S00","a:=b");
TestParsing("S00","a:={b}");
TestParsing("S00","a:={b,c}");
TestParsing("S00","a:={b;}");
TestParsing("S00","a:={b;c;}");
TestParsing("S77","m{a},m(a){b}then{c}");
TestParsing("S00","\"Hello, \\r \\{ \\} \\\"...\"");

// Floating postfixes.
TestParsing("S00","+a<b>");
TestParsing("S00","+a<b");
TestParsing("S00","[]a<b>");
TestParsing("S00","[]a<b");
TestParsing("S77","if{a}<b>then{c}");
TestParsing("S76","if(a)<b>{c}");
TestParsing("S00","a^<b>");
TestParsing("S00","a^<b");
TestParsing("S00","if{a}<b");
TestParsing("S00","a{b}<c>");
TestParsing("S00","a{b}<c");
TestParsing("S00","a{b}(c)<d>");
TestParsing("S00","a{b}(c)<d");
TestParsing("S00","a{b}<c><d>");
TestParsing("S00","a{b}<c><d");
TestParsing("S00","a{b}<c+d>");
TestParsing("S00","a{b}<c+d");
TestParsing("S00","a{b}<c+d<e+f");
TestParsing("S00","a{b}<c+d><e+f");
TestParsing("S00","a{b}<c+d<e+f>");
TestParsing("S00","a{b}<c+d><e+f>");
TestParsing("S00","a[b]<c>");
TestParsing("S00","a[b]<c");
TestParsing("S00",":t<b>");
TestParsing("S00",":t<b");

// Andrew Scheidecker's formerly exponential test case.
TestParsing("S00","A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B(A<B))))))))))))))))))))))))))))))))))))))))))))))))");

// Markup.
TestParsing("S00","<a;c>");
TestParsing("S00","<a,b;c>");
TestParsing("S00","<a{b};c>");
TestParsing("S00","<a(b);c>");
TestParsing("S00"," < a ( b ) ; c > ");
TestParsing("S00","<a.b.c>blah</c>");
TestParsing("S40","<(a)>blah</a>");
TestParsing("S00","<a(b),c(d)>blah</c/a>");
TestParsing("S00","<b.a,d.c>blah</c/a>");
TestParsing("S40","<(b),c(d)>blah</a>");
TestParsing("S40","<a(b),(c)>blah</a>");
TestParsing("S40","<1;Hello>");
TestParsing("S40","<(b);Hello>");
TestParsing("S00","<b{x:=1}>Hello</b>");
TestParsing("S00","<b{x:=1},i{y:=2};Hello>");
TestParsing("S00","<a,b{x:=1};Hello>(2)");
TestParsing("S00","<a(1);Hello>");
TestParsing("S00","<if{1};whoa>");
TestParsing("S00","<if(1)>whoa</if>");
TestParsing("S00","<if(a){junk}>b$l$a$h</if>");
TestParsing("S41","<b+c;Hello>");
TestParsing("S41","<b$;Hello>");
TestParsing("S41","<a b;Hello>");
TestParsing("S44","<b>Hello</");
TestParsing("S44","<b>Hello</2");
TestParsing("S44","<b>Hello</2>");
TestParsing("S43","<b>Hello</c>");
TestParsing("S44","<b>Hello</b");
TestParsing("S46","<b:>whoops");
TestParsing("S46","<b:> <#hi#> whoops");
TestParsing("S00","<b>Hello</b>");
TestParsing("S00","<b,i;Hello>");
TestParsing("S00","<b,i>Hello</i/b>");
TestParsing("S43","<b,i>Hello</b>");
TestParsing("S44","<b,i>Hello</i>");
TestParsing("S44","<b>Hello</>");
TestParsing("S74","<b>Hello<>");
TestParsing("S74","<b>Hello<></b>");
TestParsing("S40","<b^>Hello</b>");
TestParsing("S40","<b^;Hello>");
TestParsing("S00","<m;It's funny that <for(x:=1..9)>Hello, {x}.</for> works.>");
TestParsing("S00","<m;It's funny that <if(1=2)>nothing</if> works.>");
TestParsing("S51","<b;Hello");
TestParsing("S52","<b>Hello>");
TestParsing("S52","<b>Hello");
TestParsing("S64","<@Hello)");
TestParsing("S60","x:int<@Hello)");
TestParsing("S00","<b:>\n");
TestParsing("S00","<b:>\n   Hello\nGoodbye");
TestParsing("S00","<b:> ");
TestParsing("S00","<b:>#Hello");
TestParsing("S00","<b:><#Hello#>");
TestParsing("S00","<b:> <#hi#> #there");
TestParsing("S54","<b:>\n Hello\n There>");
TestParsing("S57","<b>Hel&abc]lo</b>");
TestParsing("S58","<List;1~2>");
TestParsing("S00","<B>bold</B>,<B;bold>,<A>bc<D>ef</D>gh</A>,f(<M>hello</M>)");
TestParsing("S00","<a{b};Hello>");
TestParsing("S00","<A(B){C}>Hello</A>");
TestParsing("S00","<a{b},c{d};Hello>");
TestParsing("S00","<a{b}>blah</a>");
TestParsing("S00","<a.(b:)C>blah</C>");
TestParsing("S00","<B:>");
TestParsing("S00","<b;Hello>,<b,i;Hi>");
TestParsing("S00","<m;Hello, {name}. Feeling <B;bold>?>");
TestParsing("S00","<a;b'c`e$f>,<List;~1~2>,[int]3,Actor<Engine>,[attr]x:=3");
TestParsing("S42","<a>Hello< /a>");
TestParsing("S44","<a>Hello</ a>");
TestParsing("S00","<a>Hello</a >");
TestParsing("S00","<m{a}{b};Hi>");
TestParsing("S00","<http;//www.epicgames.com>");
TestParsing("S00","<m;Hi>");
TestParsing("S00"," <  m   ;    Hi     >      ");
TestParsing("S00","<m:>\n Hi\n Lo");
TestParsing("S00"," <  m   :>    \n      Hi\n       Lo        ");
TestParsing("S00","<m;~a~b>");
TestParsing("S00"," <  m   ;    ~     a      ~       b        >         ");
TestParsing("S00","<a>Hi</a>");
TestParsing("S00"," <  a   >    Hi     </a      >       ");
TestParsing("S00","<a,b;Hi>");
TestParsing("S00"," <  a   ,    b     ;      Hi       >        ");
TestParsing("S00","<a,b:>\n Hi\n Lo");
TestParsing("S00"," <  a   ,    b       :>        \n  Hi\n  Lo    ");
TestParsing("S00","<a,b>Hi</b/a>");
TestParsing("S00"," <  a   ,    b     >      Hi      </b       /a        >");
TestParsing("S00"," <  a   (    b     )      ;       c        >         ");
TestParsing("S00","<a;Hi>","a{Content:=\"Hi\"}");
TestParsing("S00","<a(b);Hi>","a(b){Content:=\"Hi\"}");
TestParsing("S00","<a{b};Hi>","a{b,Content:=\"Hi\"}");
TestParsing("S00","<a{b,c};Hi>","a{b,c,Content:=\"Hi\"}");
TestParsing("S00","<a{b;c};Hi>","a{b; c; Content:=\"Hi\";}");
TestParsing("S00","<a(b){c};Hi>","a(b){c,Content:=\"Hi\"}");
TestParsing("S00","<a,b;Hi>","a{Content:=b{Content:=\"Hi\"}}");
TestParsing("S00","<a;~Hi~Lo>","a{Content:=(\"Hi\",\"Lo\")}");
TestParsing("S00","<m> abc  &   def     ;      ghi       </m>");
TestParsing("S00","<m:>\n a\n &if(a)\n &then b\n");
TestParsing("S00","<m:>\n a\n & if(a)  \n &then b\n");
TestParsing("S00","<m:>\n a\n &if(a)\n & then  b\n");
TestParsing("S00"," < b ; abc < d  ;   ef    > ghi >");
TestParsing("S00"," < b > abc < d  >   ef    </d > ghi </b >");
TestParsing("S42","</a>");
TestParsing("S42","< /a>");
TestParsing("S00","<m;ab\rcd>","m{Content:=\"ab\\ncd\"}");
TestParsing("S00","<m;ab\ncd>","m{Content:=\"ab\\ncd\"}");
TestParsing("S00","<m;ab\r\ncd>","m{Content:=\"ab\\ncd\"}");
TestParsing("S00","<m;ab\r\n\rcd>","m{Content:=\"ab\\n\\ncd\"}");
TestParsing("S00","<m;ab\r\n\ncd>","m{Content:=\"ab\\n\\ncd\"}");
TestParsing("S00","<m;ab\r\n\r\ncd>","m{Content:=\"ab\\n\\ncd\"}");
TestParsing("S00","<m;ab\n\r\ncd>","m{Content:=\"ab\\n\\ncd\"}");
TestParsing("S00","<m;ab\r\r\ncd>","m{Content:=\"ab\\n\\ncd\"}");
TestParsing("S00"," <m:> \n  a   \n    b     \n","m{Content:=\" a   \\n   b     \\n\"}");
TestParsing("S00"," <pre>\n a\n\tb</pre>");
TestParsing("S00"," <pre>\n a\n </pre>","pre{Content:=\"a\"}");
TestParsing("S00","<m;  ~ a ~ b >","m{Content:=(\" a \",\" b \")}");
TestParsing("S00","<m;\n ~a \n ~b \n>","m{Content:=(\"a \",\"b \\n\")}");
TestParsing("S00","<m>\n ~a \n ~b \n</m>","m{Content:=(\"a \",\"b \")}");
TestParsing("S74","<B>Hello<");
TestParsing("S00","<B;abc\n<#>\n <> \ndef>");
TestParsing("S74","<B;abc\n<#>\n <> \n<>");
TestParsing("S00","<B>Hel&abc;lo</B>");
TestParsing("S00","<B>Hel &  abc   ;    lo</B>");
TestParsing("S00","<B>Hel\n&abc\nlo</B>");
TestParsing("S00","<List;~1~2>");
TestParsing("S64","<not 2>");
TestParsing("S42","</a@b;c>");
TestParsing("S00","<(/Verse.org/Markup:)B>Hello</B>");
TestParsing("S00","m<a>");
TestParsing("S00","<m<a>;b>");
TestParsing("S00","<B<private>>Hello</B>");
TestParsing("S00","<m{a}do{b};c>");
TestParsing("S00","<m{a}<b>;c>");
TestParsing("S00"," <  m   {    a     }      <       b        >         ;          c           >            ");
TestParsing("S00","<m{a}<b>do{c};c>");
TestParsing("S00","<m{a}<b>do{c} ;c>");
TestParsing("S00"," <  m   {    a     }      <       b        >         do          {           c            }             ;              c               >                ");
TestParsing("S00","<m{a}<b>do{c} >  c   </m   >    ");
TestParsing("S00"," <m{a}<b>do{c} :> \n  c   \n    ");
TestParsing("S00","<\nm{a}<b>do{c} ; \nc\n>");
TestParsing("S00","<\nm{a}<b>do{c} ; c \nc\n>");
TestParsing("S00","<\nm{a}<b>do{c} \n; \nc\n>");
TestParsing("S00","<\nm{a}<b>do{c} \n> \n c \n </m > \n");
//!!TestParsing("S00","<m\n ;a>");
TestParsing("S00","<m\n;a>");
TestParsing("S00","<m{a}\n;b>");
TestParsing("S00","<m{a};\na\n>");
TestParsing("S00","<m\n; \nc\n>");
//!!TestParsing("S00","<m\n ; \nc\n>");
TestParsing("S00","<m{a}do{c} \n;c>");
TestParsing("S00","<m{a}do{c} \n; \nc\n>");
TestParsing("S00","<m{a}do{c} \n;c>");
//!!TestParsing("S00","<m\n ; \n c\n >");

// Attributes with markup.
TestParsing("S00","@<a;b>\nx:=3");
TestParsing("S00","@<a;b> x:=3");
TestParsing("S00","x:int @<a;b>");
TestParsing("S00","@<doc;Hello>\nx:=3,x:int @<doc;Hello>");
TestParsing("S00","a:=3 @<doc;Hello>");
TestParsing("S00","@<doc>blah</doc> \n a:=3");

// Raw update operations.
TestParsing("S66","x:int+=1");
TestParsing("S66","x:int-=1");
TestParsing("S66","x:int*=1");
TestParsing("S66","x:int/=1");
TestParsing("S66","a+=b");
TestParsing("S66","a*=b");
TestParsing("S66","a-=b");
TestParsing("S66","a/=b");

// Var.
TestParsing("S00","var x=9");
TestParsing("S00","var x");
TestParsing("S00"," var  x   ");
TestParsing("S00","set x+=1");
TestParsing("S00"," set  x   +=    a     +      b       ");
TestParsing("S00","var x:int");
TestParsing("S00"," var  x   :    int     ");
TestParsing("S00"," var  x   :    int     =      7       ");
TestParsing("S00"," set  x   =    x     +      1       ");
TestParsing("S00"," set  a   =    b     =      c       ");
TestParsing("S00","var a:int<3=b<c");
TestParsing("S00","var a:int:nat<c+d=b<c");

// Folds.
TestParsing("S00","-(1 when 2)","-(1 when{2})");
TestParsing("S00","return(x:=3)","return x:=3");
TestParsing("S00","return(x=>3)","return(x=>3)");
TestParsing("S00","for{x:xs while x<10}");
TestParsing("S00","for{x:xs next x+1}");
TestParsing("S00","for{x:=0 while x<10 next x+1}");
TestParsing("S00","last{x:=0 over y:ys next x+y}");
TestParsing("S00","for{x:=0 when x>=0 while x<10 next x+1}");
TestParsing("S00","return 1 when 2","return 1 when{2}");
TestParsing("S00","return{1 when 2}","return(1 when{2})");
TestParsing("S00","over,when,while,next");

// In-specifiers versus Call-specifiers.
TestParsing("S00"," 1  <   2    >     +      3       ");
TestParsing("S00"," 1  {   }    <     2      >       {        }         ");
TestParsing("S00"," 1  {   }    <     2      >       \n         {         }          ");
TestParsing("S00"," 1  <   2    >     +      3       ");
TestParsing("S00"," 1  <   2    >     :      \n       1        ");
TestParsing("S00"," 1  <   2    >     :      \n       ");
TestParsing("S00"," 1  <   2    >     ");
TestParsing("S00"," 1  <   2    >     :=      3       ");
TestParsing("S00"," 1  :   t    ");
TestParsing("S00"," 1  <   2    >     :      t       ");
TestParsing("S00"," :  1   <    2     >      +       3        ");
TestParsing("S00"," :  1   {    }     <      2       >        {         }          ");
TestParsing("S00"," :  1   {    }     <      2       >        \n         {          }           ");
TestParsing("S00"," :  1   <    2     >      +       3        ");
TestParsing("S00"," :  1   <    2     >      :       \n         1");
TestParsing("S00"," :  1   <    2     >      :       \n");
TestParsing("S00"," :  1   <    2     >      (       )        ");
TestParsing("S00"," :  1   <    2     >      (       )        :=         3");
TestParsing("S00"," :  1   <    2     >      (       )        :         t          ");
TestParsing("S00"," :  1   <    2     >      (       )        <>         3");
TestParsing("S00"," :  t   <    1     >      ");
TestParsing("S00"," :  1   (    )     <      2       >");
TestParsing("S00"," :  1   (    )     <      2       >        :=         3          ");
TestParsing("S00"," :  1   (    )     <      2       >        :         t          ");
TestParsing("S00"," :  1   (    )     <      2       >        ");
TestParsing("S00"," :  1   (    )     <      2       >        :=         3          ");
TestParsing("S00"," :  1   (    )     <      2       >        :         t          ");
TestParsing("S00"," t  <   2    >     <      3       ");
TestParsing("S00"," t  <   3    <     2      >       ");
TestParsing("S00"," t  <=   3    <      2       >        ");
TestParsing("S00"," :  t   <    2     >      <       3        ");
TestParsing("S00"," :  t   <    2     >      >       3        ");
TestParsing("S00"," :  t   <    2     >      >=       3        ");
TestParsing("S00"," :  t   <    2     >      <>       3        ");
TestParsing("S00"," :  t   <    3     <      2       >        ");
TestParsing("S00"," x  :   t    <     a      >       :        u         <          b           >=            c             ");
TestParsing("S00"," a  :   (    b     <      c       >        )         ","a:(b<c>)");
TestParsing("S00"," a  :   -    b     <      c       >        ","a:-b<c>");
TestParsing("S00"," a  :   (    -     b      )       <        c         >          ","a:-b<c>");
TestParsing("S00"," a  :   (    -     b      <       c        >         )          ","a:-(b<c>)");
TestParsing("S00"," :  t   <    a     >      <       b        >         =          c           ");
TestParsing("S00"," x  :   (    t     <      a       >        )         <          b           >            ","x:(t<a>)<b>");
TestParsing("S00"," t  <   3    <     4      <       2        >         ");
TestParsing("S00"," t  <   3    <=     4      <       2        >         ");
TestParsing("S00"," t  <=   3    <     4      <       2        >         ");
TestParsing("S00"," t  <=   3    <=     4      <       2        >         ");
TestParsing("S00","  :  t   <    3     <      4       <        2         >          ");
TestParsing("S00","  :  t   <    3     <=      4       <        2         >          ");
TestParsing("S00","  :  t   <=    3     <      4       <        2         >          ");
TestParsing("S00","  :  t   <=    3     <=      4       <        2         >          ");
